### ISSUE TITLE
No reason to query for 'contains', then call 'get'.

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#1]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/GroupOfUser.java#L32

Нет никакого смысла, а один лишь вред от вызова
```
if (map.contains(key)) {
    return map.get(key);
}
return null;
```
Вы можете сразу делать get. Если Вам приниципиально отличать null от отстутсвия элемента, убедитесь, что никогда null не добавляется в качестве значения.

**Comment by morlok1** [comment]
Действительно, я не пользуюсь тем, что get сам по себе возвращает null, если запрашиваемого элемента не существует
