### ISSUE TITLE
Use resource bundles to store localization messages

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#10]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Data/ChatMessageManager.java#L3

Используйте properties файлы, можно будет поменять сообщения без перекомпиляции проекта.

**Comment by morlok1** [comment]
Добавил properties файл с текстом сообщений, удалил теперь уже не нужный интерфейс ChatMessageManager

**Comment by TimurTechnopolis** [comment]
Отлично
