### ISSUE TITLE
Use try-with-resources block when dealing with i/o streams

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#11]
https://github.com/morlok1/OkTimetableBot/blob/4301e95168aa9d6faec44feffc9bc39dcc70f23d/src/main/java/Bot/BotHandler.java#L81

Проблема с отслеживание исключений в коде налицо. В ходе выполнения может произойти исключение, а потоки не будут закрыты. В таких ситуациях надо использовать try-with-resources блок как-то так
```
 try (
                InputStream is = httpExchange.getRequestBody();
                BufferedReader reader = new BufferedReader(new InputStreamReader(is));
                OutputStream os = httpExchange.getResponseBody();
        ) {
...
}
```

**Comment by morlok1** [comment]
Вроде как смысл уловил, обе работы с потоком обернул
