### ISSUE TITLE
Consider use of strategy design pattern to handle actions.

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#12]
https://github.com/morlok1/OkTimetableBot/blob/4301e95168aa9d6faec44feffc9bc39dcc70f23d/src/main/java/Bot/BotHandler.java#L115

Для начала покритикую подход с fuzzy логикой. Это, разумеется, здорово, что Вы рассматриваете возможность того, что пользователь может ошибиться со вводом и Вы подберёте близкую по расстоянию Левинштейна команду для данного запроса, но ведь пользователь мог и специально ошибиться, а мог написать команду, похожую на несколько одновременно. На мой взгляд, тут нужен чёткий API, гарантирующий "напишешь так, верну так-то", а никак иначе. Представьте, в REST API использовался бы похожий подход. Или лучше с username и password при логине. В общем, на мой вкус это дело опасное.

Что касается, основной претензии к этой части кода, то хотелось бы видеть отдельный компонент для каждой команды с общим интрефейсом типа
```
interface CommandAction {
boolean matches(String args);

String execute(String args);
```

тогда можно было бы создать список команд, в конце которого будет errorHelp (помощь), метод *matches* которой всегда возвращает true, а *execute* выводит пользователю сообщение 
> такой команды не существует. Выберите команду из списка...
Таким образом, можно будет легко добавить новую команду, и все команды будут изолированы друг от друга. Рассмотрите шаблон проектирования [Strategy](https://dzone.com/articles/java-the-strategy-pattern), частным случаем которого будет такой подход.

**Comment by morlok1** [comment]
По поводу fuzzy - согласен, с этим надо быть осторожным
Но т.к. в данный момент команды, на которые реагирует бот сильно отличаются, а вводиться они могут и с сенсорной клавиатуры смартфона, на которой велик шанс опечатки при небрежном наборе, я решил, что его использование оправдано.

Паттерн применил, действительно, так гораздо удобнее масштабировать и вносить правки в целом
Правда я теперь использую PropertyManager, который дублирует метод getProperty(<property name>), только у менеджера этот метод статический, чтобы не приходилось ради одного вызова загружать в каждом классе команды из ресурсов конфигурации.
Вообще при реализации паттерна я как-то увлёкся статическими методами класса
И, если честно, не знаю, плохо это или хорошо с точки зрения стилистики.
Вроде, удобно
