### ISSUE TITLE
Add shutdown hook to the application to avoid resource leaking on shutdown.

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#13]
https://github.com/morlok1/OkTimetableBot/blob/4301e95168aa9d6faec44feffc9bc39dcc70f23d/src/main/java/Bot/BotServer.java#L42

Необходимо добавить shutdown hook java.lang.Runtime#addShutdownHook, который бы закрыл http сервер, обрабатывающий http запросы извне боте при закрытии приложения (например, по ctrl+C), чтобы избежать утечки socket дескрипторов.

**Comment by morlok1** [comment]
Добавил хук с логированием: BotServer:48
