### ISSUE TITLE
Don't declare variables in advance

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#3]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/GroupOfUser.java#L52

Нет смысла объявлять переменные до того, как они будут использоваться. Это не JavaScript. И сэкономить места на стеке от этого не удастся. Если переменные нужны внутри блока, объявляйте их внутри блока. И парой строчек кода будет меньше.

**Comment by morlok1** [comment]
Вопрос - возможно я неправильно понимаю схему работы с памятью.
Если мы занесем объявление переменной внутрь цикла, то разве на каждой итерации он не будет создавать новую переменную, занимая память?

**Comment by morlok1** [comment]
Касательно конкретно этого случая - от данных переменных вовсе удалось избавиться при использовании entrySet() и модного цикла for

**Comment by TimurTechnopolis** [comment]
Декларация и выделение памяти - две разные вещи. Но даже с выделением памяти есть нюансы, связанные с оптимизациями и особенностями работы GC, где создание многих совсем короткоживущих объектов выгоднее, чем создание одного, но долгоживущего. Для циклов переменные используемые внутри цикла принято вносить внутрь цикла.
