### ISSUE TITLE
Use Map#entrySet or Map#values for iteration

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#4]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/GroupOfUser.java#L56

Используйте правильно множество для итерирования по map. В общем случае, когда нужны и ключи, и значения, правильней итерироваться по entrySet(). Тогда при необходимости получить значение, не нужно будет делать запрос в map. В вашем случае достаточно итерироваться по .values()

**Comment by morlok1** [comment]
Да, так действительно удобней, спасибо
