### ISSUE TITLE
Use switch - case for Enum values matching.

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#5]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/GroupOfUser.java#L57

Это скорее вкусовщина, но в использование switch позволит сэкономить пару символов. Выглядеть будет несколько опрятнее, да и возможности для дальнейшего расширения логики на switch выглядят перспективнее.

**Comment by morlok1** [comment]
Да, действительно, switch выглядит лучше, но у меня вопрос:
Как можно выйти из цикла, находясь в блоке switch?
Второй оператор break же не поставить

**Comment by TimurTechnopolis** [comment]
Вынести в отдельный метод и сделать return.
