### ISSUE TITLE
Delete unused code or move it to another (backup?) branch

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#6]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/GroupOfUser.java#L70

Лучше закоментированный код не в основную ветку не коммитить. Чистовая версия не должна содержать ничего лишнего.

**Comment by morlok1** [comment]
Понял, исправлено
