### ISSUE TITLE
Simplify boolean expression

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#7]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/GroupOfUser.java#L93

contains сам по себе возвращает boolean поэтому его и нужно вернуть, не усложняя код.
Да и метод лучше назвать по аналогии с **s** на конце. _contains_

**Comment by morlok1** [comment]
Сделано
