### ISSUE TITLE
Use Arrays.fill and declare a constant to avoid magic numbers.

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#8]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/UsersTimetable.java#L24

Arrays.copy идеально подходит для копирования массива. 7 - выглядит, как непонятное число. Это если подумать в неделе 7 дней. А если не думать, то лучше завести константу и DAYS_IN_WEEK и её использовать повсеместно. Заодно, если наступит [военное время](http://pricoli.info/anekdot/3501) и число дней в неделе поменяется, то можно будет в один клик всё изменить

**Comment by morlok1** [comment]
Добавлена константа
Теперь используется Array.copyOf() для копирования массива
Ццикл с заполнением массива дефолтными значениями тоже заменен на Arrays.fill()

**Comment by morlok1** [comment]
А, да, для того, цикл с заполнением массива дефолтными значениями тоже заменен на Arrays.fill()
