### ISSUE TITLE
Expose methods rather than arrays or lists or maps

### ISSUE THREAD

**Issue by TimurTechnopolis** [morlok1/OkTimetableBot#9]
https://github.com/morlok1/OkTimetableBot/blob/967c398c88930ee442dfbc11dce7ac6954a886ef/src/main/java/Domain/UsersTimetable.java#L60

Лучше в констанах сделать метод, который по индексу будет название дня недели возвращать, чем использовать массив. Массив делать доступным ещё плохо тем, что его значения можно легко перезаписать.

**Comment by morlok1** [comment]
Сделал метод доступа к массиву dayOfWeek, только однин момент:
в интерфейсе нельзя объявлять приватные поля - я поместил массив прямо в тело метода, где его никому не видно.
Но это решение какое-то... не очень
Значит ли это, что, по хорошему, нужно делать класс вместо интерфейса?

**Comment by morlok1** [comment]
И будет ли лучше в таком случае вообще все константы обернуть в геттеры?

**Comment by TimurTechnopolis** [comment]
Не все константы нужно оборачивать в геттеры, а только те, которыее не тривиально использовать, а также те, которые можно модифицировать. Такие, как списки, мапы или массивы. Если с первыми двумя есть способ - Collections.unmodifiableSmth, то с массивами так не пройдёт. Что касается нетривиальности, то я имею в виду, что у константы надо делать лишний вызов дополнительного метода.

**Comment by morlok1** [comment]
Т.е. тот способ, что выбрал я - рабочий, или всё-таки костыль?
В смысле, обернув массив в отдельный метод?

**Comment by TimurTechnopolis** [comment]
Да, получилось не очень красиво. Полагаю, в таких случаях лучше отказаться от интрефейса и перейти к final class'у с приватными филдами.
